export default [
    {
      "user_id": "8b3f9e6a-0c7e-4e2f-bc3e-7d4a5e1a91a1",
      "name": "Kevin Mwangi",
      "verified": true,
      "email": "kevin.mwangi@demo.com",
      "clerk_id": "clerk_drv_001",
      "vehicle_type": 1,
      "profile_image_slug": "profiles/kevin_mwangi.jpg",
      "id_image_slug": "ids/kevin_mwangi_id.jpg",
      "conduct_image_slug": "conduct/kevin_mwangi_clearance.jpg",
      "account_type": "driver",
      "phone": "+254712345678",
      "description": "Calm and reliable city driver",
      "driver_rating": 4.75,
      "client_rating": null,
      "trip_status": "offline"
    },
    {
      "user_id": "c2d4b2f0-5a3b-41c9-9f51-9a6d3e0f2b22",
      "name": "Brian Otieno",
      "verified": true,
      "email": "brian.otieno@demo.com",
      "clerk_id": "clerk_drv_002",
      "vehicle_type": 2,
      "profile_image_slug": "profiles/brian_otieno.jpg",
      "id_image_slug": "ids/brian_otieno_id.jpg",
      "conduct_image_slug": "conduct/brian_otieno_clearance.jpg",
      "account_type": "driver",
      "phone": "+254798112233",
      "description": "Fast response, long-distance specialist",
      "driver_rating": 4.62,
      "client_rating": null,
      "trip_status": "online"
    },
    {
      "user_id": "f91a1f3e-7c84-4c17-8f8b-1e0b9d94c333",
      "name": "Samuel Kiptoo",
      "verified": false,
      "email": "samuel.kiptoo@demo.com",
      "clerk_id": "clerk_drv_003",
      "vehicle_type": 1,
      "profile_image_slug": "profiles/samuel_kiptoo.jpg",
      "id_image_slug": "ids/samuel_kiptoo_id.jpg",
      "conduct_image_slug": "conduct/samuel_kiptoo_clearance.jpg",
      "account_type": "driver",
      "phone": "+254701998877",
      "description": "New driver, eager to serve",
      "driver_rating": 4.20,
      "client_rating": null,
      "trip_status": "offline"
    },
    {
      "user_id": "3a7c9f2b-8e9a-4e72-93c5-6a5c2bfa4444",
      "name": "Joseph Kamau",
      "verified": true,
      "email": "joseph.kamau@demo.com",
      "clerk_id": "clerk_drv_004",
      "vehicle_type": 3,
      "profile_image_slug": "profiles/joseph_kamau.jpg",
      "id_image_slug": "ids/joseph_kamau_id.jpg",
      "conduct_image_slug": "conduct/joseph_kamau_clearance.jpg",
      "account_type": "driver",
      "phone": "+254733445566",
      "description": "Luxury rides and airport transfers",
      "driver_rating": 4.90,
      "client_rating": null,
      "trip_status": "on_trip"
    }
  ]
  